This code detects the location of starting point of positions;

Input: List of offices with coordinate information + Images of corresponding offices

=> Output: List of offices with coordinate of positions

In [1]:
import pandas as pd
import os
import cv2
import numpy as np
import json
from scipy.signal import find_peaks

In [2]:
#Test Code| Version 2#
Year='1938'
Showa='13'
#Read Motherdata
path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\"+Year+"\\DataFrame_Unit.json"
with open(path, 'r') as j:
     dta = json.loads(j.read())

In [3]:
#Test code| Version 2#
df = pd.read_csv(r'C:/Users/Keitaro Ninomiya/Box/Research Notes (keitaro2@illinois.edu)/Tokyo_Jobs/Processed_Data/Index/S'+Showa+'_Unit.csv')
df=df.drop(df.columns[0], axis=1)

PositionList=['Manager','Leader','Admin','Outsource','Engineer1','Engineer2','Clerk1','Clerk2','Worker','TempWorker','Inspector','Guard','Driver','Nurse','Medic','Police','Pharma','Monitor']

In [4]:
### CLOVA FUNCTION ###
import requests
import uuid
import time
import json
import cv2
import base64

def Clova(Dept,Office,Unit,ImagePage,LeftEdge,RightEdge):
    api_url = 'https://deelieyxuc.apigw.ntruss.com/custom/v1/1972/ebd01bcbf693d069817622e9839e20914143c7d0d8953eddee40e8b0af96c95b/general'
    secret_key = 'S1NmVXpYZlJ0cGJ0ZEFRZXVlbkRkaHFReE9FcHNTQ0U='

    path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\"+Year+"\\"+Dept+"\\"+Office+"\\"+Unit+"\\"
    stream = open(path+"Image"+str(ImagePage)+'.png', "rb")
    bytes = bytearray(stream.read())
    numpyarray = np.asarray(bytes, dtype=np.uint8)
    img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
    HH,WW=img.shape[:2]
    cropped = img[0:100,LeftEdge:RightEdge]
    
    try:    
        temp_path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Temp\\"
        cv2.imwrite(temp_path+"Temp.jpg",cropped)
        with open(temp_path+"Temp.jpg",'rb') as f:
            file_data = f.read()

        request_json = {
                'images': [
                    {
                        'format': 'jpg',
                        'name': 'demo',
                        'data':base64.b64encode(file_data).decode()}],
                'requestId': str(uuid.uuid4()),
                'version': 'V2',
                'timestamp': int(round(time.time() * 1000)),
                'lang':'ja'
                }
        payload = json.dumps(request_json).encode("UTF-8")
        headers = {'X-OCR-SECRET': secret_key,
                  'Content-Type': 'application/json'}
        response = requests.request("POST", api_url, headers=headers, data = payload)
        Json=json.loads(response.text)['images'][0]
        if 'fields' not in list(Json.keys()):
            return 'NA'
        if Json['fields']==[]:
            return 'NA'
        if Json['fields']!=[]:
            Text=''.join([d['inferText'] for d in Json['fields']])
        return Text
    except:
        return ([])

In [5]:
# Function for returning x coordinate of Position name
def Detect_Position(Frame,Position):
    ### Get Coordinates ###
    try:
        if Position=='Manager': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('主事|主|毒|寿|畫')])
            return(Edge)

        if Position=='Leader': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('課長|課')])
            return(Edge)

        if Position=='Engineer1': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('技師|師|技術|支')])
            return(Edge)

        if Position=='Engineer2': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('技手|手|个')])
            return(Edge)

        if Position=='Admin': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('事務員')])
            return(Edge)

        if Position=='Outsource': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('嘱託員|嘱託|嘱|託|呪')])
            return(Edge)

        if Position=='Clerk1': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('皆|書記|言')])
            return(Edge)

        if Position=='Clerk2': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('収納|收納')])
            return(Edge)

        if Position=='Clerk3': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('社會書')])
            return(Edge)

        if Position=='Worker': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('雇|届|扉|履|雁|展|扁|羅|風|厨')])
            return(Edge)

        if Position=='TempWorker': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('臨時')])
            return(Edge)

        if Position=='Inspector': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('視学|視學')])
            return(Edge)
        
        if Position=='Guard': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('守衛長')])
            return(Edge)
        
        if Position=='Driver': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('運轉|轉')])
            return(Edge)
        
        if Position=='Nurse': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('保健婦')])
            return(Edge)

        if Position=='Medic': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('醫員')])
            return(Edge)

        if Position=='Police': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('警員')])
            return(Edge)

        if Position=='Pharma': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('調薬員|藥員')])
            return(Edge)

        if Position=='Monitor': 
            Edge=int(Frame['Second'][Frame['Text'].str.contains('監視')])
            return(Edge)
    except:
        return 'NA'

class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

In [6]:
def Clova2(Dept,Office,Unit,ImagePage):
    api_url = 'https://deelieyxuc.apigw.ntruss.com/custom/v1/2038/42ead006bc8f828b6079063216fa47aa99c9761923e949392e11eec8784c8db2/infer'
    secret_key = 'bUdOUG5CR3FJb0VqRmZrSE9EWUtIem5LcFllRGxiUnA='

    path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\"+Year+"\\"+Dept+"\\"+Office+"\\"+Unit+"\\"
    stream = open(path+"Image"+str(ImagePage)+'.png', "rb")
    bytes = bytearray(stream.read())
    numpyarray = np.asarray(bytes, dtype=np.uint8)
    img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
    HH,WW=img.shape[:2]
    cropped = img[0:HH,0:WW]
    
    temp_path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Temp\\"
    cv2.imwrite(temp_path+"Temp.jpg",cropped)
    with open(temp_path+"Temp.jpg",'rb') as f:
        file_data = f.read()
    
    request_json = {
            'images': [
                {
                    'format': 'jpg',
                    'name': 'demo',
                    'data':base64.b64encode(file_data).decode()}],
            'requestId': str(uuid.uuid4()),
            'version': 'V2',
            'timestamp': int(round(time.time() * 1000)),
            'lang':'ja'
            }
    payload = json.dumps(request_json).encode("UTF-8")
    headers = {'X-OCR-SECRET': secret_key,
              'Content-Type': 'application/json'}
    response = requests.request("POST", api_url, headers=headers, data = payload)
    Json=json.loads(response.text)
    
    return Json

In [7]:
def Organize(Dict,EndPage):
    ##Add Ending information
    Frame=pd.DataFrame.from_dict(Dict,orient='index')
    Frame=Frame.sort_values(by = ['Starting_Page', 'XLocation'], ascending = [True, False])
    Frame["EndLocation"]=list(Frame['XLocation'].shift(-1))[:-1]+list([0])
    Frame["EndPage"]=list(Frame['Starting_Page'].shift(-1))[:-1]+list([EndPage])
    Frame=Frame.to_dict('index')
    return(Frame)

In [8]:
def Show(Position,Page):
    PosiList=list(Dict.keys())
    path="C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\"+Year+'\\'+Dept+"\\"+Office+"\\"+Unit+"\\"+Position+"\\Image"+str(Page)+".png"
    stream = open(path, "rb")
    bytes = bytearray(stream.read())
    numpyarray = np.asarray(bytes, dtype=np.uint8)
    img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
    HH=img.shape[:2][0]
    for Posi in PosiList:
        XCord=Dict[Posi]['XLocation']
        cv2.line(img, (XCord,0), (XCord,HH), (0,0,0), 3)
    cv2.imshow(Office,img)
    cv2.waitKey(0)

In [9]:
def Find_cell(Dept,Office,Unit,ImagePage):
    path='C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\'
    path=os.path.join(path,Year,Dept,Office,Unit)
    stream = open(path+"\\Image"+str(ImagePage)+'.png', "rb")
    bytes = bytearray(stream.read())
    numpyarray = np.asarray(bytes, dtype=np.uint8)
    img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)

    HH,WW=img.shape[:2]
    Top=150
    while Top>50:        
        cropped=img[0:Top, 0:WW]

        # convert to grayscale
        gray = cv2.cvtColor(cropped,cv2.COLOR_BGR2GRAY)
        # threshold gray image
        thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)[1]

        # count number of non-zero pixels in each column and row. 
        countCol = np.count_nonzero(thresh, axis=0)

        ### This finds the height of the lowest valley
        peaks, _ = find_peaks(countCol, distance=15)

        Frame={'First':peaks,'Second':np.roll(peaks,-1).tolist()[:-1]+list([WW])}
        Frame=pd.DataFrame.from_dict(Frame,orient='index').transpose()
        ColNum=len(Frame)
        Frame['Text']=list(map(Clova,[Dept]*ColNum,[Office]*ColNum,[Unit]*ColNum,[ImagePage]*ColNum,Frame['First'],Frame['Second']))

        #Find Starting X coordinates of Positions.
        #First Loop: 
        CordList=list(map(Detect_Position,[Frame]*len(PositionListNow),PositionListNow))
        Positions= {PositionListNow[i]:CordList[i] for i in range(len(PositionListNow))}
        Positions = {k:v for k,v in Positions.items() if v}    

        PosiList = list(Positions.keys())
        CordList = list(Positions.values())

        CordDictNow= {PosiList[i]: {'XLocation':CordList[i],'Starting_Page':ImagePage} for i in range(len(PosiList))}
        CordDictNow = {k:v for k,v in CordDictNow.items() if v['XLocation']!='NA'}
        if len(CordDictNow)<=len(CordDict):
            break
        else:
            print('updating...'+str(len(CordDict))+' to '+str(len(CordDictNow)))
            display((CordDictNow.keys()))
            CordDict.update(CordDictNow)
            Top=Top-20
    print('Finished first attempt at scanning...')
    print('Result of Initial Scan was...')
    display(CordDict)

    CordDictNow['First']={'XLocation':HH}
    Frame=pd.DataFrame.from_dict(CordDictNow,orient='index')
    Frame=Frame.sort_values(by=['XLocation'],ascending=False)
    Frame['EndLocation']=Frame['XLocation'].shift(-1)
    Frame.loc[Frame.index[-1], 'EndLocation'] = 0
    Frame["EndLocation"].apply(np.int64)
    
    print('Detected Positions were...')
    display(Frame)

    RowNum=len(Frame)
    print('Refining Scans...')
    
    CordDict2={}
    for i in range(0,RowNum):    
        Row=Frame.iloc[i]
        Righ=int(Row['XLocation'])
        Left=int(Row['EndLocation'])
        if abs(Righ-Left)<5:
            continue

        cropped=img[0:Top+30,Left:Righ]
        HH,WW=cropped.shape[:2]
        
        # convert to grayscale
        gray = cv2.cvtColor(cropped,cv2.COLOR_BGR2GRAY)
        # threshold gray image
        thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)[1]

        # count number of non-zero pixels in each column and row. 
        countCol = np.count_nonzero(thresh, axis=0)

        ### This finds the height of the lowest valley
        peaks, _ = find_peaks(countCol, distance=15)
        peaks = peaks+Left

        Frame2={'First':peaks,'Second':np.roll(peaks,-1).tolist()[:-1]+list([WW+Left])}
        Frame2=pd.DataFrame.from_dict(Frame2,orient='index').transpose()
        if len(Frame2)<=1:
            continue
        
        ColNum=len(Frame2)
        Frame2['Text']=list(map(Clova,[Dept]*ColNum,[Office]*ColNum,[Unit]*ColNum,[ImagePage]*ColNum,Frame2['First'],Frame2['Second']))
        
        #Find Starting X coordinates of Positions.
        #First Loop: 
        CordList=list(map(Detect_Position,[Frame2]*len(PositionListNow),PositionListNow))
        Positions= {PositionListNow[i]:CordList[i] for i in range(len(PositionListNow))}
        Positions = {k:v for k,v in Positions.items() if v}   

        PosiList = list(Positions.keys())
        CordList = list(Positions.values())

        CordDictNow2= {PosiList[i]: {'XLocation':CordList[i],'Starting_Page':ImagePage} for i in range(len(PosiList))}
        CordDictNow2 = {k:v for k,v in CordDictNow2.items() if v['XLocation']!='NA'}
        print('Scanned '+str(i+1)+'th crop...')
        print('Results is...')
        display(CordDictNow2)
        #cv2.imshow(str(i)+'th Image',cropped)
        #cv2.waitKey(0)

        CordDict2.update(CordDictNow2)
    CordDict.update(CordDict2)
    return(CordDict)

In [10]:
def hconcat_resize_min(im_list, interpolation=cv2.INTER_CUBIC):
    h_min = min(im.shape[0] for im in im_list)
    im_list_resize = [cv2.resize(im, (int(im.shape[1] * h_min / im.shape[0]), h_min), interpolation=interpolation)
                      for im in im_list]
    return cv2.hconcat(im_list_resize)

def Check(df,dta,K):
    for n in range(0,K):
        #Extract key info of office
        Row  = df.iloc[n]

        ###Collect Location information###
        Dept=Row["Dept"]
        Office=Row["Office"]
        Unit=Row["Unit"]
        
        print('['+str(n)+',"'+Dept+'","'+Office+'","'+Unit+'"]')      
        StrPage=1
        try:
            EndPage=dta[Year][Dept][Office]['Units'][Unit]['EndPage']-dta[Year][Dept][Office]['Units'][Unit]['Page']+1

            path=os.path.join('C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level',Year,Dept,Office,Unit)
            stream = open(path+"\\Image"+str(StrPage)+'.png', "rb")
            bytes = bytearray(stream.read())
            numpyarray = np.asarray(bytes, dtype=np.uint8)
            img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
            HH,WW=img.shape[:2]
            oldimg=img.copy()[0:200,0:WW]

            for Page in range(StrPage+1,EndPage+1):
                path=os.path.join('C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level',Year,Dept,Office,Unit)
                stream = open(path+"\\Image"+str(Page)+'.png', "rb")
                bytes = bytearray(stream.read())
                numpyarray = np.asarray(bytes, dtype=np.uint8)
                newimg = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
                HH,WW=newimg.shape[:2]
                newimg = newimg[0:200,0:WW]
                oldimg= hconcat_resize_min((newimg,oldimg))
            oldimg=cv2.copyMakeBorder(oldimg,20,20,20,20,cv2.BORDER_CONSTANT)

            PosiList=list(dta[Year][Dept][Office]['Units'][Unit]['Positions'].keys())
            for Posi in PosiList:
                StrLoc=int(dta[Year][Dept][Office]['Units'][Unit]['Positions'][Posi]['XLocation'])
                StrPage=int(dta[Year][Dept][Office]['Units'][Unit]['Positions'][Posi]['Starting_Page'])

                path=os.path.join('C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level',Year,Dept,Office,Unit)
                stream = open(path+"\\Image"+str(StrPage)+'.png', "rb")
                bytes = bytearray(stream.read())
                numpyarray = np.asarray(bytes, dtype=np.uint8)
                newimg = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
                HH,WW=newimg.shape[:2]
                Annotate=newimg.copy()[0:200,0:WW]
                cv2.line(Annotate,(StrLoc,0),(StrLoc,HH),(255,0,0),2)
                Annotate=cv2.copyMakeBorder(Annotate,20,20,20,20,cv2.BORDER_CONSTANT)
                oldimg=hconcat_resize_min((Annotate,oldimg))

            oldimg=cv2.resize(oldimg, None, fx = 0.60, fy = 0.60)
            cv2.imshow(Dept+Office,oldimg)
            cv2.waitKey(0)
        except:
            continue
    cv2.destroyAllWindows()
    cv2.waitKey(0)

In [ ]:
FailedList=[]
for n in range(0,len(df)+1):
    PositionListNow=PositionList.copy()
    #Extract key info of office
    Row  = df.iloc[n]

    ###Collect Location information###
    Dept=Row["Dept"]
    Office=Row["Office"]
    Unit=Row['Unit']
    print('['+str(n)+',"'+Dept+'","'+Office+'","'+Unit+'"]')

    StrPage=1
    EndPage=dta[Year][Dept][Office]['Units'][Unit]['EndPage']-dta[Year][Dept][Office]['Units'][Unit]['Page']+1
    Page_Range=range(StrPage,EndPage+1)

    CordDict={}
    for ImagePage in Page_Range:
        try:
            CordDict.update(Find_cell(Dept,Office,Unit,ImagePage))
        except:
            print('Failed at '+Dept+Office+Unit)
            FailedList.append((n,Dept,Office,Unit))
            continue
            
    if len(CordDict)==0:
        FailedList.append((n,Dept,Office,Unit))
        continue
    dta[Year][Dept][Office]['Units'][Unit]['Positions']=Organize(CordDict,EndPage)

[0,"Admin","人事課","庶務掛"]
updating...0 to 1

dict_keys(['Manager'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 69, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          470            NaN         69.0
Manager         69            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{}

updating...1 to 2

dict_keys(['Worker', 'TempWorker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 69, 'Starting_Page': 1},
 'Worker': {'XLocation': 66, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 31, 'Starting_Page': 2}}

Detected Positions were...

            XLocation  Starting_Page  EndLocation
First             470            NaN         66.0
Worker             66            2.0         31.0
TempWorker         31            2.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 2th crop...
Results is...

{'Worker': {'XLocation': 64, 'Starting_Page': 2}}

[1,"Admin","人事課","人事掛"]
updating...0 to 5

dict_keys(['Engineer1', 'Engineer2', 'Clerk1', 'Worker', 'TempWorker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer1': {'XLocation': 48, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 48, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 48, 'Starting_Page': 1},
 'Worker': {'XLocation': 48, 'Starting_Page': 1},
 'TempWorker': {'XLocation': 48, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          470            NaN        108.0
Manager        108            1.0         92.0
Clerk1          92            1.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 3th crop...
Results is...

{'Engineer1': {'XLocation': 84, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 84, 'Starting_Page': 1},
 'Worker': {'XLocation': 84, 'Starting_Page': 1}}

[2,"Admin","人事課","給與掛"]
updating...0 to 2

dict_keys(['Engineer2', 'Clerk1'])

updating...2 to 3

dict_keys(['Outsource', 'Worker', 'TempWorker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer2': {'XLocation': 111, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 92, 'Starting_Page': 1},
 'Outsource': {'XLocation': 111, 'Starting_Page': 1},
 'Worker': {'XLocation': 111, 'Starting_Page': 1},
 'TempWorker': {'XLocation': 111, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          470            NaN        111.0
Manager        111            1.0         86.0
Clerk1          86            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 80, 'Starting_Page': 1}}

[3,"Admin","人事課","福利掛"]
updating...0 to 1

dict_keys(['Manager'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 108, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        470          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 108, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        487          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[4,"Admin","文書課","庶務掛"]
updating...0 to 2

dict_keys(['Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Clerk1': {'XLocation': 53, 'Starting_Page': 1},
 'Worker': {'XLocation': 30, 'Starting_Page': 1}}

Detected Positions were...

        XLocation  Starting_Page  EndLocation
First         487            NaN         53.0
Clerk1         53            1.0         30.0
Worker         30            1.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[5,"Admin","文書課","法規掛"]
Finished first attempt at scanning...
Result of Initial Scan was...

{}

Detected Positions were...

       XLocation  EndLocation
First        487          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Clerk1': {'XLocation': 128, 'Starting_Page': 1}}

updating...1 to 3

dict_keys(['Manager', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Clerk1': {'XLocation': 145, 'Starting_Page': 2},
 'Manager': {'XLocation': 165, 'Starting_Page': 2},
 'Worker': {'XLocation': 82, 'Starting_Page': 2}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          487            NaN        165.0
Manager        165            2.0        145.0
Clerk1         145            2.0         89.0
Worker          89            2.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 140, 'Starting_Page': 2}}

Scanned 4th crop...
Results is...

{'Worker': {'XLocation': 82, 'Starting_Page': 2}}

[6,"Admin","文書課","公報掛"]
updating...0 to 4

dict_keys(['Manager', 'Outsource', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 145, 'Starting_Page': 1},
 'Outsource': {'XLocation': 37, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 110, 'Starting_Page': 1},
 'Worker': {'XLocation': 55, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        487          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Manager': {'XLocation': 145, 'Starting_Page': 1},
 'TempWorker': {'XLocation': 37, 'Starting_Page': 1},
 'Nurse': {'XLocation': 37, 'Starting_Page': 1},
 'Medic': {'XLocation': 37, 'Starting_Page': 1}}

[7,"Admin","文書課","圖書掛"]
updating...0 to 3

dict_keys(['Manager', 'Engineer1', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 143, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 95, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 121, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            487            NaN        152.0
Manager          152            1.0        119.0
Clerk1           119            1.0         95.0
Engineer1         95            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{'Manager': {'XLocation': 143, 'Starting_Page': 1}}

Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 117, 'Starting_Page': 1}}

Scanned 4th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 143, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 95, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 117, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Outsource': {'XLocation': 274, 'Starting_Page': 2},
 'Engineer1': {'XLocation': 126, 'Starting_Page': 2},
 'Engineer2': {'XLocation': 126, 'Starting_Page': 2},
 'Pharma': {'XLocation': 126, 'Starting_Page': 2}}

[8,"企画局","庶務課","庶務掛"]
updating...0 to 2

dict_keys(['Manager', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 63, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 19, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          468            NaN         63.0
Manager         63            1.0         19.0
Clerk1          19            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{'Manager': {'XLocation': 63, 'Starting_Page': 1}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 63, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 19, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Worker': {'XLocation': 35, 'Starting_Page': 2}}

[9,"企画局","庶務課","議事掛"]
updating...0 to 3

dict_keys(['Manager', 'Engineer2', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 137, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 62, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 121, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          468            NaN        137.0
Manager        137            1.0        121.0
Clerk1         121            1.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 3th crop...
Results is...

{'Engineer2': {'XLocation': 62, 'Starting_Page': 1}}

[10,"企画局","財務課","管理掛"]
updating...0 to 2

dict_keys(['Manager', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 97, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 75, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          480            NaN         94.0
Manager         94            1.0         75.0
Clerk1          75            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{}

[11,"企画局","財務課","豫算掛"]
Finished first attempt at scanning...
Result of Initial Scan was...

{}

Detected Positions were...

       XLocation  EndLocation
First        480          0.0

Refining Scans...
Failed at 企画局財務課豫算掛
[12,"企画局","財務課","主事八千掛"]
updating...0 to 2

dict_keys(['Manager', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 162, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 134, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          480            NaN        164.0
Manager        164            1.0        146.0
Clerk1         146            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 134, 'Starting_Page': 1}}

[13,"企画局","財務課","調査掛"]
updating...0 to 5

dict_keys(['Manager', 'Outsource', 'Clerk1', 'Worker', 'TempWorker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 178, 'Starting_Page': 1},
 'Outsource': {'XLocation': 28, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 160, 'Starting_Page': 1},
 'Worker': {'XLocation': 79, 'Starting_Page': 1},
 'TempWorker': {'XLocation': 45, 'Starting_Page': 1}}

Detected Positions were...

            XLocation  Starting_Page  EndLocation
First             480            NaN        178.0
Manager           178            1.0         79.0
Worker             79            1.0         46.0
TempWorker         46            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{'Manager': {'XLocation': 178, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 160, 'Starting_Page': 1}}

Scanned 4th crop...
Results is...

{'Outsource': {'XLocation': 28, 'Starting_Page': 1},
 'TempWorker': {'XLocation': 46, 'Starting_Page': 1}}

[14,"企画局","統計課","統計掛"]
updating...0 to 2

dict_keys(['Manager', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 249, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 227, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          469            NaN        249.0
Manager        249            1.0        213.0
Clerk1         213            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 213, 'Starting_Page': 1}}

[15,"企画局","統計課","産業統計掛"]
updating...0 to 2

dict_keys(['Manager', 'Engineer1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            469            NaN        194.0
Manager          194            1.0        174.0
Engineer1        174            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        469          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

updating...5 to 6

dict_keys(['Manager', 'Leader', 'Engineer1', 'Engineer2', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 372, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 372, 'Starting_Page': 3},
 'Worker': {'XLocation': 372, 'Starting_Page': 3}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            476            NaN        379.0
Engineer1        379            3.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Scanned 2th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
Manager        514            4.0        514.0
Clerk1         514            4.0        476.0
First          476            NaN          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{}

Scanned 3th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

        XLocation  Starting_Page  EndLocation
First         448            NaN        128.0
Worker        128            5.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 2th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          448            NaN         97.0
Manager         97            6.0         97.0
Clerk1          97            6.0         97.0
Worker          97            6.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 4th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

       XLocation  EndLocation
First        469          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

       XLocation  EndLocation
First        469          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 468, 'Starting_Page': 3},
 'Engineer1': {'XLocation': 372, 'Starting_Page': 3},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 468, 'Starting_Page': 3},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2},
 'Leader': {'XLocation': 372, 'Starting_Page': 3},
 'Engineer2': {'XLocation': 468, 'Starting_Page': 3},
 'Worker': {'XLocation': 468, 'Starting_Page': 3}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[16,"企画局","統計課","調査掛"]
Finished first attempt at scanning...
Result of Initial Scan was...

{}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Manager': {'XLocation': 106, 'Starting_Page': 1}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 106, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        474          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[17,"企画局","統計課","人口統計掛"]
Finished first attempt at scanning...
Result of Initial Scan was...

{}

Detected Positions were...

       XLocation  EndLocation
First        474          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[18,"企画局","統計課","市勢統計掛"]
Finished first attempt at scanning...
Result of Initial Scan was...

{}

Detected Positions were...

       XLocation  EndLocation
First        474          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Manager': {'XLocation': 103, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 79, 'Starting_Page': 1},
 'Worker': {'XLocation': 41, 'Starting_Page': 1}}

[19,"企画局","都市計画課","事務掛"]
updating...0 to 5

dict_keys(['Manager', 'Outsource', 'Engineer2', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 319, 'Starting_Page': 1},
 'Outsource': {'XLocation': 54, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 139, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 284, 'Starting_Page': 1},
 'Worker': {'XLocation': 104, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            474            NaN        319.0
Manager          319            1.0        284.0
Clerk1           284            1.0        138.0
Engineer2        138            1.0        104.0
Worker           104            1.0         54.0
Outsource         54            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{}

Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 284, 'Starting_Page': 1}}

Scanned 5th crop...
Results is...

{'Worker': {'XLocation': 104, 'Starting_Page': 1}}

Scanned 6th crop...
Results is...

{'Outsource': {'XLocation': 54, 'Starting_Page': 1}}

[20,"企画局","都市計画課","計畫掛"]
updating...0 to 1

dict_keys(['Engineer1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer1': {'XLocation': 161, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        474          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Engineer1': {'XLocation': 161, 'Starting_Page': 1}}

updating...1 to 3

dict_keys(['Engineer2', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer1': {'XLocation': 161, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 185, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 261, 'Starting_Page': 2},
 'Worker': {'XLocation': 104, 'Starting_Page': 2}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            470            NaN        261.0
Clerk1           261            2.0        185.0
Engineer2        185            2.0        103.0
Worker           103            2.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

Scanned 2th crop...
Results is...

{'Clerk1': {'XLocation': 261, 'Starting_Page': 2}}

Scanned 3th crop...
Results is...

{'Engineer2': {'XLocation': 185, 'Starting_Page': 2}}

Scanned 4th crop...
Results is...

{'Worker': {'XLocation': 103, 'Starting_Page': 2}}

[21,"企画局","都市計画課","整地掛"]
updating...0 to 3

dict_keys(['Engineer1', 'Engineer2', 'Clerk1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer1': {'XLocation': 196, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 56, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 111, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            470            NaN        196.0
Engineer1        196            1.0        120.0
Clerk1           120            1.0         56.0
Engineer2         56            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{'Engineer1': {'XLocation': 187, 'Starting_Page': 1}}

Scanned 3th crop...
Results is...

{'Clerk1': {'XLocation': 111, 'Starting_Page': 1}}

Scanned 4th crop...
Results is...

{'Engineer2': {'XLocation': 56, 'Starting_Page': 1}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Engineer1': {'XLocation': 187, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 56, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 111, 'Starting_Page': 1}}

Detected Positions were...

       XLocation  EndLocation
First        470          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

[22,"企画局","都市計画課","町名整理掛"]
updating...0 to 5

dict_keys(['Manager', 'Engineer1', 'Engineer2', 'Clerk1', 'Worker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 353, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 153, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 104, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 326, 'Starting_Page': 1},
 'Worker': {'XLocation': 224, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            470            NaN        353.0
Manager          353            1.0        332.0
Clerk1           332            1.0        153.0
Engineer1        153            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Engineer2': {'XLocation': 274, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 326, 'Starting_Page': 1},
 'Worker': {'XLocation': 224, 'Starting_Page': 1}}

Scanned 4th crop...
Results is...

{'Engineer1': {'XLocation': 153, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 104, 'Starting_Page': 1}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 353, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 153, 'Starting_Page': 1},
 'Engineer2': {'XLocation': 104, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 326, 'Starting_Page': 1},
 'Worker': {'XLocation': 224, 'Starting_Page': 1}}

Detected Positions were...

            XLocation  Starting_Page  EndLocation
First             462            NaN        106.0
TempWorker        106            2.0          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{'Worker': {'XLocation': 139, 'Starting_Page': 2}}

Scanned 2th crop...
Results is...

{}

[23,"経理局","会計課","庶務掛"]
updating...0 to 4

dict_keys(['Manager', 'Clerk1', 'Worker', 'Guard'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 204, 'Starting_Page': 1},
 'Clerk1': {'XLocation': 160, 'Starting_Page': 1},
 'Worker': {'XLocation': 46, 'Starting_Page': 1},
 'Guard': {'XLocation': 63, 'Starting_Page': 1}}

Detected Positions were...

         XLocation  Starting_Page  EndLocation
First          462            NaN        204.0
Manager        204            1.0        160.0
Clerk1         160            1.0         67.0
Guard           67            1.0         46.0
Worker          46            1.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{}

In [ ]:
Check(df,dta,40)

In [21]:
dta[Year]['Admin']['人事課']['Units']["庶務掛"]

{'Page': 1,
 'StartLocation': 101,
 'EndPage': 2,
 'EndLocation': 402,
 'Page_Range': [1, 2],
 'Positions': {'Manager': {'XLocation': 69,
   'Starting_Page': 1,
   'EndLocation': 64.0,
   'EndPage': 2.0},
  'Worker': {'XLocation': 64,
   'Starting_Page': 2,
   'EndLocation': 31.0,
   'EndPage': 2.0},
  'TempWorker': {'XLocation': 31,
   'Starting_Page': 2,
   'EndLocation': 0.0,
   'EndPage': 2.0}}}

In [72]:
for n in range(0,50):
    #Extract key info of office
    Row  = df2.iloc[n]

    ###Collect Location information###
    Dept=Row["Dept"]
    Office=Row["Office"]
    Unit=Row['Unit']
    
    StrPage=1
    EndPage=int(dta[Year][Dept][Office]['Units'][Unit]['EndPage'])-int(dta[Year][Dept][Office]['Units'][Unit]['Page'])+1
    print('Page Range is '+str(StrPage)+str(EndPage))
    
    path='C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\'
    path=os.path.join(path,Year,Dept,Office,Unit)
    stream = open(path+"\\Image"+str(StrPage)+'.png', "rb")
    bytes = bytearray(stream.read())
    numpyarray = np.asarray(bytes, dtype=np.uint8)
    img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
    oldimg=img.copy()
    
    for Page in range(StrPage+1,EndPage+1):
        stream = open(path+"\\Image"+str(Page)+'.png', "rb")
        bytes = bytearray(stream.read())
        numpyarray = np.asarray(bytes, dtype=np.uint8)
        newimg = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
        oldimg=np.concatenate((newimg,oldimg), axis=1)
    oldimg=cv2.copyMakeBorder(oldimg,20,20,20,20,cv2.BORDER_CONSTANT)
    
    PosiList=list(dta[Year][Dept][Office]['Units'][Unit]['Positions'].keys())
    for Posi in PosiList:        
        StrLoc=int(dta[Year][Dept][Office]['Units'][Unit]['Positions'][Posi]['XLocation'])
        Page=int(dta[Year][Dept][Office]['Units'][Unit]['Positions'][Posi]['Starting_Page'])

        path='C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Raw_Data\\Office_Level\\'
        path=os.path.join(path,Year,Dept,Office,Unit)
        stream = open(path+"\\Image"+str(Page)+'.png', "rb")
        bytes = bytearray(stream.read())
        numpyarray = np.asarray(bytes, dtype=np.uint8)
        img = cv2.imdecode(numpyarray, cv2.IMREAD_UNCHANGED)
        HH,WW=img.shape[:2]

        Annotate=img.copy()
        cv2.line(Annotate,(StrLoc,0),(StrLoc,HH),(255,0,0),2)
        Annotate=cv2.copyMakeBorder(Annotate,20,20,20,20,cv2.BORDER_CONSTANT)
        oldimg=np.concatenate((Annotate,oldimg), axis=1)
    cv2.imshow(Dept+Office+Unit+Posi,oldimg)
    cv2.waitKey(0)

Page Range is 12
Page Range is 12
Page Range is 12
Page Range is 11
Page Range is 11
Page Range is 11
Page Range is 11

IndexError: single positional indexer is out-of-bounds

In [75]:
df2

    Dept Office Unit  Year    Position
0  Admin    人事課  庶務掛  1938     Manager
1  Admin    人事課  庶務掛  1938      Worker
2  Admin    人事課  庶務掛  1938  TempWorker
3  Admin    人事課  人事掛  1938     Manager
4  Admin    人事課  人事掛  1938      Clerk1
5  Admin    人事課  給與掛  1938   Engineer2
6  Admin    人事課  給與掛  1938      Clerk1

In [12]:
json_object = json.dumps(dta, indent=4,
                        cls=NpEncoder)
save_path='C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\'+str(Year)+'\\'
with open(save_path+"DataFrame_Position.json", "w") as outfile:
    outfile.write(json_object)

In [13]:
df2=pd.DataFrame(columns=['Dept','Office','Unit','Year','Position'])
for n in range(0,len(df)):
    Row=df.iloc[n]
    Office=Row['Office']
    Dept=Row['Dept']
    Unit=Row['Unit']
    try:
        PosiList=list(dta[Year][Dept][Office]['Units'][Unit]['Positions'].keys())
        for Posi in PosiList:
            NewRow={'Office':Office,'Dept':Dept,'Unit':Unit,'Year':Year,'Position':Posi}
            df2 = df2.append(NewRow, ignore_index = True)
    except:
        continue
df2.to_csv(r'C:/Users/Keitaro Ninomiya/Box/Research Notes (keitaro2@illinois.edu)/Tokyo_Jobs/Processed_Data/Index/S'+Showa+'_Final.csv')

C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)
C:\Temp\ipykernel_25336\2579514942.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(NewRow, ignore_index = True)

In [52]:
PositionListNow=PositionList.copy()
n=15
#Extract key info of office
Row  = df.iloc[n]
###Collect Location information###
Dept=Row["Dept"]
Office=Row["Office"]
Unit=Row['Unit']

StrPage=1
EndPage=dta[Year][Dept][Office]['Units'][Unit]['EndPage']-dta[Year][Dept][Office]['Units'][Unit]['Page']+1
Page_Range=range(StrPage,EndPage+1)

CordDict={}
for ImagePage in Page_Range:
    CordDictNow=Find_cell(Dept,Office,Unit,ImagePage)
    display(CordDictNow)
    CordDict.update(CordDictNow)
dta[Year][Dept][Office]['Units'][Unit]['Positions']=Organize(CordDict,EndPage)

updating...0 to 2

dict_keys(['Manager', 'Engineer1'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

Detected Positions were...

           XLocation  Starting_Page  EndLocation
First            469            NaN        194.0
Manager          194            1.0        174.0
Engineer1        174            1.0          0.0

Refining Scans...
Scanned 3th crop...
Results is...

{'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1}}

updating...2 to 4

dict_keys(['Outsource', 'Clerk1', 'Worker', 'TempWorker'])

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 293, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

            XLocation  Starting_Page  EndLocation
First             469            NaN        457.0
Clerk1            457            2.0        292.0
TempWorker        292            2.0        259.0
Outsource         259            2.0          0.0

Refining Scans...
Scanned 2th crop...
Results is...

{'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2}}

Scanned 4th crop...
Results is...

{'Outsource': {'XLocation': 259, 'Starting_Page': 2}}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        476          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        476          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        448          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        448          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        469          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        469          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Finished first attempt at scanning...
Result of Initial Scan was...

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

Detected Positions were...

       XLocation  EndLocation
First        468          0.0

Refining Scans...
Scanned 1th crop...
Results is...

{}

{'Manager': {'XLocation': 193, 'Starting_Page': 1},
 'Engineer1': {'XLocation': 152, 'Starting_Page': 1},
 'Outsource': {'XLocation': 259, 'Starting_Page': 2},
 'Clerk1': {'XLocation': 457, 'Starting_Page': 2},
 'Worker': {'XLocation': 423, 'Starting_Page': 2},
 'TempWorker': {'XLocation': 293, 'Starting_Page': 2}}

In [16]:
FailRate=len(FailedList)/len(df)
if len(FailedList)/len(df)<0.2:
    print('Fantastic!! Success Rate is '+str(1-(len(FailedList)/len(df))))
else:
    print('残念...Success Rate is '+str(1-(len(FailedList)/len(df))))
DF=pd.read_csv('C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\Records.csv')
DF.loc[int(Year)-1934, 'Position'] = 1-FailRate
DF.to_csv('C:\\Users\\Keitaro Ninomiya\\Box\\Research Notes (keitaro2@illinois.edu)\\Tokyo_Jobs\\Processed_Data\\Records.csv',index=False )

Fantastic!! Success Rate is 0.9881656804733728

{'Admin': {'秘書課': {'Starting_Page': 2,
   'Office_X1': 480,
   'Ending_Page': 2,
   'Office_X2': 178,
   'Page_Range': [2]},
  '人事課': {'Starting_Page': 2,
   'Office_X1': 168,
   'Ending_Page': 4,
   'Office_X2': 377,
   'Page_Range': [2, 3, 4],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 101,
     'EndPage': 2,
     'EndLocation': 402,
     'Page_Range': [1, 2]},
    '人事掛': {'Page': 2,
     'StartLocation': 402,
     'EndPage': 2,
     'EndLocation': 267,
     'Page_Range': [2]},
    '給與掛': {'Page': 2,
     'StartLocation': 267,
     'EndPage': 2,
     'EndLocation': 132,
     'Page_Range': [2]},
    '福利掛': {'Page': 2,
     'StartLocation': 132,
     'EndPage': 3,
     'EndLocation': 0,
     'Page_Range': [2, 3]},
    'List': ['庶務掛', '人事掛', '給與掛', '福利掛']}},
  '文書課': {'Starting_Page': 4,
   'Office_X1': 367,
   'Ending_Page': 6,
   'Office_X2': 145,
   'Page_Range': [4, 5, 6],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 315,
     'EndPage': 1,
     'EndLocation': 205,
     'Page_Range': [1]},
    '法規掛': {'Page': 1,
     'StartLocation': 205,
     'EndPage': 2,
     'EndLocation': 345,
     'Page_Range': [1, 2]},
    '公報掛': {'Page': 2,
     'StartLocation': 345,
     'EndPage': 2,
     'EndLocation': 173,
     'Page_Range': [2]},
    '圖書掛': {'Page': 2,
     'StartLocation': 173,
     'EndPage': 3,
     'EndLocation': 0,
     'Page_Range': [2, 3]},
    'List': ['庶務掛', '法規掛', '公報掛', '圖書掛']}}},
 '中央卸売市場': {'監理課': {'Starting_Page': 289,
   'Office_X1': 285,
   'Ending_Page': 293,
   'Office_X2': 453,
   'Page_Range': [289, 290, 291, 292, 293],
   'Units': {'應務掛': {'Page': 1,
     'StartLocation': 230,
     'EndPage': 2,
     'EndLocation': 416,
     'Page_Range': [1, 2]},
    '監理掛': {'Page': 2,
     'StartLocation': 416,
     'EndPage': 3,
     'EndLocation': 528,
     'Page_Range': [2, 3]},
    '冷藏庫掛': {'Page': 3,
     'StartLocation': 528,
     'EndPage': 3,
     'EndLocation': 298,
     'Page_Range': [3]},
    '神田分場(下3四二一五·八一二)掛': {'Page': 3,
     'StartLocation': 298,
     'EndPage': 4,
     'EndLocation': 378,
     'Page_Range': [3, 4]},
    '江東分場(本二二〇〇)掛': {'Page': 4,
     'StartLocation': 378,
     'EndPage': 4,
     'EndLocation': 248,
     'Page_Range': [4]},
    '荏原分場(大崎16六五六)掛': {'Page': 4,
     'StartLocation': 248,
     'EndPage': 4,
     'EndLocation': 84,
     'Page_Range': [4]},
    '豊島分場(大七七三三)掛': {'Page': 4,
     'StartLocation': 84,
     'EndPage': 5,
     'EndLocation': 0,
     'Page_Range': [4, 5]},
    'List': ['應務掛',
     '監理掛',
     '冷藏庫掛',
     '神田分場(下3四二一五·八一二)掛',
     '江東分場(本二二〇〇)掛',
     '荏原分場(大崎16六五六)掛',
     '豊島分場(大七七三三)掛']}},
  '会計課': {'Starting_Page': 293,
   'Office_X1': 443,
   'Ending_Page': 294,
   'Office_X2': 227,
   'Page_Range': [293, 294],
   'Units': {'計畫掛': {'Page': 1,
     'StartLocation': 384,
     'EndPage': 1,
     'EndLocation': 176,
     'Page_Range': [1]},
    '調査掛': {'Page': 1,
     'StartLocation': 176,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [1, 2]},
    'List': ['計畫掛', '調査掛']}}},
 '企画局': {'庶務課': {'Starting_Page': 6,
   'Office_X1': 135,
   'Ending_Page': 7,
   'Office_X2': 255,
   'Page_Range': [6, 7],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 91,
     'EndPage': 2,
     'EndLocation': 168,
     'Page_Range': [1, 2]},
    '議事掛': {'Page': 2,
     'StartLocation': 168,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [2]},
    'List': ['庶務掛', '議事掛']}},
  '企画課': {'Starting_Page': 7,
   'Office_X1': 245,
   'Ending_Page': 8,
   'Office_X2': 217,
   'Page_Range': [7, 8]},
  '財務課': {'Starting_Page': 8,
   'Office_X1': 207,
   'Ending_Page': 9,
   'Office_X2': 165,
   'Page_Range': [8, 9],
   'Units': {'管理掛': {'Page': 1,
     'StartLocation': 150,
     'EndPage': 1,
     'EndLocation': 30,
     'Page_Range': [1]},
    '豫算掛': {'Page': 1,
     'StartLocation': 30,
     'EndPage': 2,
     'EndLocation': 374,
     'Page_Range': [1, 2]},
    '主事八千掛': {'Page': 2,
     'StartLocation': 374,
     'EndPage': 2,
     'EndLocation': 208,
     'Page_Range': [2]},
    '調査掛': {'Page': 2,
     'StartLocation': 208,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [2]},
    'List': ['管理掛', '豫算掛', '主事八千掛', '調査掛']}},
  '統計課': {'Starting_Page': 9,
   'Office_X1': 155,
   'Ending_Page': 20,
   'Office_X2': 71,
   'Page_Range': [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
   'Units': {'統計掛': {'Page': 2,
     'StartLocation': 494,
     'EndPage': 2,
     'EndLocation': 220,
     'Page_Range': [2]},
    '産業統計掛': {'Page': 2,
     'StartLocation': 220,
     'EndPage': 11,
     'EndLocation': 130,
     'Page_Range': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]},
    '調査掛': {'Page': 11,
     'StartLocation': 130,
     'EndPage': 12,
     'EndLocation': 272,
     'Page_Range': [11, 12]},
    '人口統計掛': {'Page': 12,
     'StartLocation': 272,
     'EndPage': 12,
     'EndLocation': 129,
     'Page_Range': [12]},
    '市勢統計掛': {'Page': 12,
     'StartLocation': 129,
     'EndPage': 12,
     'EndLocation': 0,
     'Page_Range': [12]},
    'List': ['統計掛', '産業統計掛', '調査掛', '人口統計掛', '市勢統計掛']}},
  '都市計画課': {'Starting_Page': 20,
   'Office_X1': 61,
   'Ending_Page': 24,
   'Office_X2': 311,
   'Page_Range': [20, 21, 22, 23, 24],
   'Units': {'事務掛': {'Page': 2,
     'StartLocation': 531,
     'EndPage': 2,
     'EndLocation': 189,
     'Page_Range': [2]},
    '計畫掛': {'Page': 2,
     'StartLocation': 189,
     'EndPage': 3,
     'EndLocation': 225,
     'Page_Range': [2, 3]},
    '整地掛': {'Page': 3,
     'StartLocation': 225,
     'EndPage': 4,
     'EndLocation': 381,
     'Page_Range': [3, 4]},
    '町名整理掛': {'Page': 4,
     'StartLocation': 381,
     'EndPage': 5,
     'EndLocation': 0,
     'Page_Range': [4, 5]},
    'List': ['事務掛', '計畫掛', '整地掛', '町名整理掛']}}},
 '保健局': {'庶務課': {'Starting_Page': 101,
   'Office_X1': 334,
   'Ending_Page': 102,
   'Office_X2': 83,
   'Page_Range': [101, 102],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 269,
     'EndPage': 1,
     'EndLocation': 135,
     'Page_Range': [1]},
    '監理掛': {'Page': 1,
     'StartLocation': 135,
     'EndPage': 2,
     'EndLocation': 324,
     'Page_Range': [1, 2]},
    '經理掛': {'Page': 2,
     'StartLocation': 324,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [2]},
    'List': ['庶務掛', '監理掛', '經理掛']}},
  '衛生課': {'Starting_Page': 102,
   'Office_X1': 73,
   'Ending_Page': 116,
   'Office_X2': 26,
   'Page_Range': [102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116],
   'Units': {'社會衛生掛': {'Page': 1,
     'StartLocation': 22,
     'EndPage': 2,
     'EndLocation': 283,
     'Page_Range': [1, 2]},
    '岩淵診療所(赤羽二四〇一)掛': {'Page': 2,
     'StartLocation': 283,
     'EndPage': 2,
     'EndLocation': 92,
     'Page_Range': [2]},
    '代々龝診療所(四谷 五四一八)掛': {'Page': 2,
     'StartLocation': 92,
     'EndPage': 3,
     'EndLocation': 398,
     'Page_Range': [2, 3]},
    '中野診療所(中63二〇八九)掛': {'Page': 3,
     'StartLocation': 398,
     'EndPage': 3,
     'EndLocation': 273,
     'Page_Range': [3]},
    '目黒診療所(花四四八六二)掛': {'Page': 3,
     'StartLocation': 273,
     'EndPage': 3,
     'EndLocation': 166,
     'Page_Range': [3]},
    '世田谷診療所(世田谷二九八一)掛': {'Page': 3,
     'StartLocation': 166,
     'EndPage': 3,
     'EndLocation': 82,
     'Page_Range': [3]},
    '向島診療所(四二二一四四)掛': {'Page': 3,
     'StartLocation': 82,
     'EndPage': 4,
     'EndLocation': 430,
     'Page_Range': [3, 4]},
    '向島診療所隔田出張所(税別)HOLL)掛': {'Page': 4,
     'StartLocation': 430,
     'EndPage': 4,
     'EndLocation': 337,
     'Page_Range': [4]},
    '尾久診療所(下60七七五五)掛': {'Page': 4,
     'StartLocation': 337,
     'EndPage': 4,
     'EndLocation': 204,
     'Page_Range': [4]},
    '防疫掛': {'Page': 4,
     'StartLocation': 204,
     'EndPage': 8,
     'EndLocation': 392,
     'Page_Range': [4, 5, 6, 7, 8]},
    '豫防掛': {'Page': 8,
     'StartLocation': 392,
     'EndPage': 8,
     'EndLocation': 255,
     'Page_Range': [8]},
    '大塚健康相談所(小五五〇三五)掛': {'Page': 8,
     'StartLocation': 255,
     'EndPage': 9,
     'EndLocation': 455,
     'Page_Range': [8, 9]},
    '澁谷健康相談所(青三三〇一八)掛': {'Page': 9,
     'StartLocation': 455,
     'EndPage': 9,
     'EndLocation': 276,
     'Page_Range': [9]},
    '下谷健康相談所(第2四七七〇)掛': {'Page': 9,
     'StartLocation': 276,
     'EndPage': 9,
     'EndLocation': 191,
     'Page_Range': [9]},
    '本所健康相談所(四74四五〇四)掛': {'Page': 9,
     'StartLocation': 191,
     'EndPage': 9,
     'EndLocation': 16,
     'Page_Range': [9]},
    '中野健康相渋所中国八九掛': {'Page': 9,
     'StartLocation': 16,
     'EndPage': 10,
     'EndLocation': 361,
     'Page_Range': [9, 10]},
    '大井健康相談所(大森三三九八八)掛': {'Page': 10,
     'StartLocation': 361,
     'EndPage': 10,
     'EndLocation': 237,
     'Page_Range': [10]},
    '尾久健康相談所(下60七〇五八)掛': {'Page': 10,
     'StartLocation': 237,
     'EndPage': 10,
     'EndLocation': 117,
     'Page_Range': [10]},
    '神田健康相談所(神四一七〇八)掛': {'Page': 10,
     'StartLocation': 117,
     'EndPage': 11,
     'EndLocation': 361,
     'Page_Range': [10, 11]},
    '向島健康相談所(最12五五九九五九三)掛': {'Page': 11,
     'StartLocation': 361,
     'EndPage': 11,
     'EndLocation': 218,
     'Page_Range': [11]},
    '牛込健康相談所(牛d五五六六)掛': {'Page': 11,
     'StartLocation': 218,
     'EndPage': 11,
     'EndLocation': 69,
     'Page_Range': [11]},
    '目黒健康相談所(花原四四八六二)掛': {'Page': 11,
     'StartLocation': 69,
     'EndPage': 12,
     'EndLocation': 442,
     'Page_Range': [11, 12]},
    '麻布健康相談所(赤43五一五一)掛': {'Page': 12,
     'StartLocation': 442,
     'EndPage': 12,
     'EndLocation': 270,
     'Page_Range': [12]},
    '杉並健康相談所(荻窪四九八八)掛': {'Page': 12,
     'StartLocation': 270,
     'EndPage': 13,
     'EndLocation': 472,
     'Page_Range': [12, 13]},
    '深川健康相談所(本03九二二五)掛': {'Page': 13,
     'StartLocation': 472,
     'EndPage': 13,
     'EndLocation': 355,
     'Page_Range': [13]},
    '寄生蟲病診療所掛': {'Page': 13,
     'StartLocation': 355,
     'EndPage': 13,
     'EndLocation': 301,
     'Page_Range': [13]},
    '寄生虫病診療所足立出張所掛': {'Page': 13,
     'StartLocation': 301,
     'EndPage': 13,
     'EndLocation': 246,
     'Page_Range': [13]},
    '第一トラホーム治療所掛': {'Page': 13,
     'StartLocation': 246,
     'EndPage': 13,
     'EndLocation': 171,
     'Page_Range': [13]},
    '第二トラホーム治療所掛': {'Page': 13,
     'StartLocation': 171,
     'EndPage': 13,
     'EndLocation': 102,
     'Page_Range': [13]},
    '第一班トラホーム治療所掛': {'Page': 13,
     'StartLocation': 102,
     'EndPage': 13,
     'EndLocation': 36,
     'Page_Range': [13]},
    '第二班トラホーム治療所(撰文サ国産粮掛': {'Page': 13,
     'StartLocation': 36,
     'EndPage': 14,
     'EndLocation': 424,
     'Page_Range': [13, 14]},
    '第三班トラホーム治療所掛': {'Page': 14,
     'StartLocation': 424,
     'EndPage': 14,
     'EndLocation': 342,
     'Page_Range': [14]},
    '第四班トラホーム治療所掛': {'Page': 14,
     'StartLocation': 342,
     'EndPage': 14,
     'EndLocation': 263,
     'Page_Range': [14]},
    '第五班トラホーム治療所掛': {'Page': 14,
     'StartLocation': 263,
     'EndPage': 14,
     'EndLocation': 184,
     'Page_Range': [14]},
    '第六班トラホーム治療所掛': {'Page': 14,
     'StartLocation': 184,
     'EndPage': 14,
     'EndLocation': 108,
     'Page_Range': [14]},
    '小兒衞生掛': {'Page': 14,
     'StartLocation': 108,
     'EndPage': 15,
     'EndLocation': 415,
     'Page_Range': [14, 15]},
    '日本橋小兒保健所(呼出茅恒大二一○(有馬))掛': {'Page': 15,
     'StartLocation': 415,
     'EndPage': 15,
     'EndLocation': 327,
     'Page_Range': [15]},
    '目黒小兒保健所(花四四八六二)掛': {'Page': 15,
     'StartLocation': 327,
     'EndPage': 15,
     'EndLocation': 234,
     'Page_Range': [15]},
    '保健指導掛': {'Page': 15,
     'StartLocation': 234,
     'EndPage': 15,
     'EndLocation': 0,
     'Page_Range': [15]},
    'List': ['社會衛生掛',
     '岩淵診療所(赤羽二四〇一)掛',
     '代々龝診療所(四谷 五四一八)掛',
     '中野診療所(中63二〇八九)掛',
     '目黒診療所(花四四八六二)掛',
     '世田谷診療所(世田谷二九八一)掛',
     '向島診療所(四二二一四四)掛',
     '向島診療所隔田出張所(税別)HOLL)掛',
     '尾久診療所(下60七七五五)掛',
     '防疫掛',
     '豫防掛',
     '大塚健康相談所(小五五〇三五)掛',
     '澁谷健康相談所(青三三〇一八)掛',
     '下谷健康相談所(第2四七七〇)掛',
     '本所健康相談所(四74四五〇四)掛',
     '中野健康相渋所中国八九掛',
     '大井健康相談所(大森三三九八八)掛',
     '尾久健康相談所(下60七〇五八)掛',
     '神田健康相談所(神四一七〇八)掛',
     '向島健康相談所(最12五五九九五九三)掛',
     '牛込健康相談所(牛d五五六六)掛',
     '目黒健康相談所(花原四四八六二)掛',
     '麻布健康相談所(赤43五一五一)掛',
     '杉並健康相談所(荻窪四九八八)掛',
     '深川健康相談所(本03九二二五)掛',
     '寄生蟲病診療所掛',
     '寄生虫病診療所足立出張所掛',
     '第一トラホーム治療所掛',
     '第二トラホーム治療所掛',
     '第一班トラホーム治療所掛',
     '第二班トラホーム治療所(撰文サ国産粮掛',
     '第三班トラホーム治療所掛',
     '第四班トラホーム治療所掛',
     '第五班トラホーム治療所掛',
     '第六班トラホーム治療所掛',
     '小兒衞生掛',
     '日本橋小兒保健所(呼出茅恒大二一○(有馬))掛',
     '目黒小兒保健所(花四四八六二)掛',
     '保健指導掛']}},
  '公園課': {'Starting_Page': 116,
   'Office_X1': 16,
   'Ending_Page': 122,
   'Office_X2': 161,
   'Page_Range': [116, 117, 118, 119, 120, 121, 122],
   'Units': {'事務掛': {'Page': 2,
     'StartLocation': 468,
     'EndPage': 2,
     'EndLocation': 252,
     'Page_Range': [2]},
    '公園掛': {'Page': 2,
     'StartLocation': 252,
     'EndPage': 3,
     'EndLocation': 433,
     'Page_Range': [2, 3]},
    'E其解即時田井武家川口霸江内緒田沼渡邊指市大一掛': {'Page': 3,
     'StartLocation': 433,
     'EndPage': 3,
     'EndLocation': 188,
     'Page_Range': [3]},
    '計畫掛': {'Page': 3,
     'StartLocation': 188,
     'EndPage': 5,
     'EndLocation': 464,
     'Page_Range': [3, 4, 5]},
    '東部出張所(本日3九九〇一)掛': {'Page': 5,
     'StartLocation': 464,
     'EndPage': 5,
     'EndLocation': 244,
     'Page_Range': [5]},
    '南部出張所(與60二六六)掛': {'Page': 5,
     'StartLocation': 244,
     'EndPage': 6,
     'EndLocation': 410,
     'Page_Range': [5, 6]},
    '西部出張所(府中七九)掛': {'Page': 6,
     'StartLocation': 410,
     'EndPage': 6,
     'EndLocation': 221,
     'Page_Range': [6]},
    '北部出張所(下二二二〇一)掛': {'Page': 6,
     'StartLocation': 221,
     'EndPage': 7,
     'EndLocation': 301,
     'Page_Range': [6, 7]},
    '大島公園事務所掛': {'Page': 7,
     'StartLocation': 301,
     'EndPage': 7,
     'EndLocation': 0,
     'Page_Range': [7]},
    'List': ['事務掛',
     '公園掛',
     'E其解即時田井武家川口霸江内緒田沼渡邊指市大一掛',
     '計畫掛',
     '東部出張所(本日3九九〇一)掛',
     '南部出張所(與60二六六)掛',
     '西部出張所(府中七九)掛',
     '北部出張所(下二二二〇一)掛',
     '大島公園事務所掛']}}},
 '土木局': {'庶務課': {'Starting_Page': 171,
   'Office_X1': 316,
   'Ending_Page': 173,
   'Office_X2': 226,
   'Page_Range': [171, 172, 173],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 257,
     'EndPage': 1,
     'EndLocation': 27,
     'Page_Range': [1]},
    '工務掛': {'Page': 1,
     'StartLocation': 27,
     'EndPage': 2,
     'EndLocation': 309,
     'Page_Range': [1, 2]},
    '用度掛': {'Page': 2,
     'StartLocation': 309,
     'EndPage': 2,
     'EndLocation': 59,
     'Page_Range': [2]},
    '檢査掛': {'Page': 2,
     'StartLocation': 59,
     'EndPage': 3,
     'EndLocation': 0,
     'Page_Range': [2, 3]},
    'List': ['庶務掛', '工務掛', '用度掛', '檢査掛']}},
  '道路管理課': {'Starting_Page': 173,
   'Office_X1': 216,
   'Ending_Page': 177,
   'Office_X2': 282,
   'Page_Range': [173, 174, 175, 176, 177],
   'Units': {'管理掛': {'Page': 1,
     'StartLocation': 156,
     'EndPage': 2,
     'EndLocation': 54,
     'Page_Range': [1, 2]},
    '第一修繕掛': {'Page': 2,
     'StartLocation': 54,
     'EndPage': 3,
     'EndLocation': 85,
     'Page_Range': [2, 3]},
    '第二修繕掛': {'Page': 3,
     'StartLocation': 85,
     'EndPage': 4,
     'EndLocation': 273,
     'Page_Range': [3, 4]},
    '路線掛': {'Page': 4,
     'StartLocation': 273,
     'EndPage': 5,
     'EndLocation': 0,
     'Page_Range': [4, 5]},
    'List': ['管理掛', '第一修繕掛', '第二修繕掛', '路線掛']}},
  '道路建設課': {'Starting_Page': 177,
   'Office_X1': 272,
   'Ending_Page': 181,
   'Office_X2': 347,
   'Page_Range': [177, 178, 179, 180, 181],
   'Units': {'計畫掛': {'Page': 1,
     'StartLocation': 218,
     'EndPage': 3,
     'EndLocation': 454,
     'Page_Range': [1, 2, 3]},
    '設計掛': {'Page': 3,
     'StartLocation': 454,
     'EndPage': 4,
     'EndLocation': 322,
     'Page_Range': [3, 4]},
    '工事掛': {'Page': 4,
     'StartLocation': 322,
     'EndPage': 5,
     'EndLocation': 0,
     'Page_Range': [4, 5]},
    'List': ['計畫掛', '設計掛', '工事掛']}},
  '河川課': {'Starting_Page': 181,
   'Office_X1': 337,
   'Ending_Page': 199,
   'Office_X2': 120,
   'Page_Range': [181,
    182,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    191,
    192,
    193,
    194,
    195,
    196,
    197,
    198,
    199],
   'Units': {'管理掛': {'Page': 1,
     'StartLocation': 278,
     'EndPage': 1,
     'EndLocation': 70,
     'Page_Range': [1]},
    '設計掛': {'Page': 1,
     'StartLocation': 70,
     'EndPage': 2,
     'EndLocation': 388,
     'Page_Range': [1, 2]},
    '河川工事掛': {'Page': 2,
     'StartLocation': 388,
     'EndPage': 3,
     'EndLocation': 104,
     'Page_Range': [2, 3]},
    '橋梁工事掛': {'Page': 3,
     'StartLocation': 104,
     'EndPage': 5,
     'EndLocation': 494,
     'Page_Range': [3, 4, 5]},
    '無務掛': {'Page': 5,
     'StartLocation': 494,
     'EndPage': 5,
     'EndLocation': 111,
     'Page_Range': [5]},
    ')經理掛': {'Page': 5,
     'StartLocation': 111,
     'EndPage': 6,
     'EndLocation': 275,
     'Page_Range': [5, 6]},
    '道路掛': {'Page': 6,
     'StartLocation': 275,
     'EndPage': 7,
     'EndLocation': 322,
     'Page_Range': [6, 7]},
    '橋梁掛': {'Page': 7,
     'StartLocation': 322,
     'EndPage': 19,
     'EndLocation': 0,
     'Page_Range': [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]},
    'List': ['管理掛', '設計掛', '河川工事掛', '橋梁工事掛', '無務掛', ')經理掛', '道路掛', '橋梁掛']}}},
 '小河内貯水池建設事務所': {'庶務課': {'Starting_Page': 305,
   'Office_X1': 300,
   'Ending_Page': 306,
   'Office_X2': 18,
   'Page_Range': [305, 306],
   'Units': {'庶務掛': {'Page': 1,
     'StartLocation': 205,
     'EndPage': 2,
     'EndLocation': 386,
     'Page_Range': [1, 2]},
    '用地掛': {'Page': 2,
     'StartLocation': 386,
     'EndPage': 2,
     'EndLocation': 211,
     'Page_Range': [2]},
    '經理掛': {'Page': 2,
     'StartLocation': 211,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [2]},
    'List': ['庶務掛', '用地掛', '經理掛']}},
  '工事課': {'Starting_Page': 306,
   'Office_X1': 8,
   'Ending_Page': 309,
   'Office_X2': 207,
   'Page_Range': [306, 307, 308, 309],
   'Units': {'設計掛': {'Page': 2,
     'StartLocation': 391,
     'EndPage': 3,
     'EndLocation': 390,
     'Page_Range': [2, 3]},
    '内線掛': {'Page': 3,
     'StartLocation': 390,
     'EndPage': 3,
     'EndLocation': 90,
     'Page_Range': [3]},
    '機械掛': {'Page': 3,
     'StartLocation': 90,
     'EndPage': 4,
     'EndLocation': 0,
     'Page_Range': [3, 4]},
    'List': ['設計掛', '内線掛', '機械掛']}}},
 '市民動員部': {'国民総精神総動員課': {'Starting_Page': 264,
   'Office_X1': 339,
   'Ending_Page': 265,
   'Office_X2': 282,
   'Page_Range': [264, 265],
   'Units': {'應務掛': {'Page': 1,
     'StartLocation': 225,
     'EndPage': 1,
     'EndLocation': 73,
     'Page_Range': [1]},
    '實行掛': {'Page': 1,
     'StartLocation': 73,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [1, 2]},
    'List': ['應務掛', '實行掛']}},
  '防衛課': {'Starting_Page': 265,
   'Office_X1': 272,
   'Ending_Page': 267,
   'Office_X2': 431,
   'Page_Range': [265, 266, 267],
   'Units': {'事務掛': {'Page': 1,
     'StartLocation': 218,
     'EndPage': 2,
     'EndLocation': 477,
     'Page_Range': [1, 2]},
    '防務掛': {'Page': 2,
     'StartLocation': 477,
     'EndPage': 2,
     'EndLocation': 339,
     'Page_Range': [2]},
    '計畫掛': {'Page': 2,
     'StartLocation': 339,
     'EndPage': 3,
     'EndLocation': 0,
     'Page_Range': [2, 3]},
    'List': ['事務掛', '防務掛', '計畫掛']}},
  '軍事援護課': {'Starting_Page': 267,
   'Office_X1': 421,
   'Ending_Page': 268,
   'Office_X2': 463,
   'Page_Range': [267, 268],
   'Units': {'統制掛': {'Page': 1,
     'StartLocation': 341,
     'EndPage': 1,
     'EndLocation': 188,
     'Page_Range': [1]},
    '計畫掛': {'Page': 1,
     'StartLocation': 188,
     'EndPage': 2,
     'EndLocation': 0,
     'Page_Range': [1, 2]},
    'List': ['統制掛', '計畫掛']}}},
 '教育局': {'庶務課': {'Starting_Page': 57,
   'Office_X1': 106,
   'Ending_Page': 58,
   'Office_X2': 40,
   'Page_Range': [57, 58],
   'Units': {'庶務掛': {'Page': 1,